<?php $api_fields = array(
'aweber_api_key',
'getresponse_api_key',
'hcaptcha_private_key',
'hcaptcha_public_key',
'mailchimp_api_key',
'mailerlite_api_key',
'recaptcha_private_key',
'recaptcha_public_key',
'recaptcha3_private_key',
'recaptcha3_public_key',
'sendinblue_api_key',
'sendy_api_key',
'sendy_url',
'sg_autorepondeur_account_id',
'sg_autorepondeur_activation_code');